add env output by option

diff --git a/.github/workflows/publish_preview.yml b/.github/workflows/publish_preview.yml
--- a/.github/workflows/publish_preview.yml
+++ b/.github/workflows/publish_preview.yml
@@ -18,6 +18,7 @@ jobs:
       base_branch: ${{ steps.detect_pr.outputs.base_branch }}
       sha: ${{ steps.detect_pr.outputs.sha }}
       pr_number: ${{ steps.detect_pr.outputs.pr_number }}
+      env: ${{ steps.detect_env.outputs.env || steps.detect_pr.outputs.base_branch }}
     steps:
       - name: Detect application name
         id: detect_app
@@ -44,6 +45,24 @@ jobs:
           echo "base_branch=$(echo $PR | jq -r '.base.ref')" >> $GITHUB_OUTPUT
           echo "sha=$(echo $PR | jq -r '.head.sha')" >> $GITHUB_OUTPUT
           echo "pr_number=$(echo $PR | jq -r '.number')" >> $GITHUB_OUTPUT
+
+      - name: Check env option
+        id: detect_env
+        if: contains(github.event.comment.body, '--env ')
+        run: |
+          env_name=$(echo $input | sed -n 's/.*--env \([^ ]*\).*/\1/p')
+
+          valid_env_names=(stg qa dev)
+          for valid_env_name in "${valid_env_names[@]}"; do
+            if [[ $env_name == $valid_env_name ]]; then
+              echo "Valid env name: $env_name"
+              echo "env=$env_name" >> $GITHUB_OUTPUT
+              exit 0
+            fi
+          done
+
+          echo "Invalid env option: $env_name"
+          exit 1
 
       - name: Check if base branch is env branch
         run: |
@@ -74,3 +93,4 @@ jobs:
           echo "branch=${{ needs.detect-command.outputs.branch }}"
           echo "sha=${{ needs.detect-command.outputs.sha }}"
           echo "pr_number=${{ needs.detect-command.outputs.pr_number }}"
+          echo "env=${{ needs.detect-command.outputs.env }}"
